version: '3'

services:
  server:
    image: node:16
    working_dir: /app
    volumes:
      - ./server:/app
      - type: bind
        source: ./app/dist
        target: /web-dist
        read_only: true
    environment:
      PORT: 80
      HOST: 0.0.0.0
    # restart: always
    depends_on:
      - web
    ports:
      - "8080:80"
    command: [sh, -c, npm install && npm run start]

  web:
    image: node:16
    working_dir: /app
    volumes:
      - ./app:/app
    # restart: always
    command: [sh, -c, npm install && npm run start]
