version: '3'

services:
  server:
    image: node:16
    working_dir: /app
    volumes:
      - ./server:/app
      - ./app/dist:/web-dist
    environment:
      PORT: 80
      HOST: 0.0.0.0
    # restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    command: [sh, -c, npm install && npm run start]

  web:
    image: node:16
    working_dir: /app
    volumes:
      - ./app:/app
    # restart: always
    command: [sh, -c, npm install && npm run start]
