version: '3'

services:
  server:
    image: node:16
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      PORT: 8000
      HOST: 0.0.0.0
      APP_URL: http://web/
    # restart: always
    ports:
      - "8000:8000"
    command: [sh, -c, npm install && npm run start]

  web:
    image: node:16
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      PORT: 80
    # restart: always
    command: [sh, -c, npm install && npm run start]
